### PR TITLE
Some SDRAM + clocking updates

### PR DESCRIPTION
**Pull request by gyurco**
Microdisc controller would be better with 24MHz clock/clock enables, then you'll avoid dreaded messages like:
Warning (332060): Node: oricatmos:oricatmos|Microdisc:inst_microdisc|PH2_2 was determined to be a clock but was found without an associated clock assignment.

This means the part of the design which using this clock won't be timing-optimized.

### CODE REVIEW

**Review by rampa069 — APPROVED** [review]
not sure if the AY is going to clock OK. Also doubts, as the microdisc controller gets the PHI2_2 deriving a 32 Mhz clock..... I am going to merge and test what happens.

Thanks!

**Comment by gyurco** [comment]
If the original AY in the Oric clocked by the 1 MHz clock, then it should be OK with the 1 MHz clock enable.

**Comment by gyurco** [comment]
About PHI2_2 and wd1793: you're using this clock signal as a clock enable - wrong
Didn't check the waveform and period, but these clocks are usually 8 MHz originally - it can be derived from 24 MHz, too (not that the wd1793 module is cycle exact in any way).

**Comment by rampa069** [comment]
Believe it or no, this phase is used on the oric for nmap and disk drives (in the schematic) i have tried to drive the signal from the phi2 clock, but this doesnt work. so i have used the same strategy than the microdisk with PHI2_2 

Your patches are working. so you were right!  ill try to derive from 24 and kill the 32 clock. Thank You very much!

**Comment by gyurco** [comment]
I didn't write that the disc controller is not clocked by phi2_2 - but the wd1793 core's ce signal is a **clock enable**, **not** a clock!
Some material about clock enables:
https://www.fpga4student.com/2017/08/how-to-generate-clock-enable-signal.html

The same strategy used in the ULA, too: there's the phi2 signal, which is a clock (and best to avoid using it as a clock in the FPGA), and the phi2_en, which is the corresponding clock enable in the 24MHz clock domain.

**Comment by rampa069** [comment]
yes, i know but the REAL wd1793 is clocked that way.  negated phi2_2 so i assume it has to be the clock enable.

**Comment by retrocrypta** [comment]
I still get a BLACK screen when launching core. Still not working.

**Comment by retrocrypta** [comment]
blackscreenORic

not working on MiST with Micron Ram

**Comment by gyurco** [comment]
@rampa069 Please read the link I posted, and notice the difference between a clock and clock enable.
The best would be to visualise in e.g. SignalTap II the ULA's phi2 and phi2_en signals, it's easer to understand.

**Comment by gyurco** [comment]
@retrocrypta  there are still some timing violations, mostly from 32MHz->24MHz clock domain crossings, that could be one of the reasons. You can even try to synthesize with more optimizations, e.g. standard fit instead of fast fit, optimize for speed, etc...

**Comment by retrocrypta** [comment]
I'll take a look at options, selecting extras. synthesizing now

**Comment by gyurco** [comment]
Btw, phi2_2 looks like 1MHz. Is it really used for the FDC? Writing to DD MFM disk requires 8 MHz clock, even the old FM disks need 4 MHz.

**Comment by retrocrypta** [comment]
What synthesis options do you propose?
some clue?

At the moment I have not managed to make it work.


atmosbad
oric1bad

**Comment by gyurco** [comment]
https://homepages.uni-regensburg.de/~hep09515/oric1/microdisc-2.gif
In this schematics, the WD1793 gets a 4 MHz clock (8 MHz from a crystal, divided by 2).

**Comment by gyurco** [comment]
@retrocrypta I would try to compile without the microdisc module, if it causes the issue.

**Comment by gyurco** [comment]
In wd1793 instantiation:
EDSK => 1
Are there Oric disk images in EDSK format (that's used by the Amstrad CPC and ZX +3).

**Comment by retrocrypta** [comment]
At first attempt, without microdisc, does not work. The result is the same.
Now trying to see CLK's

**Comment by retrocrypta** [comment]
> In wd1793 instantiation:
> EDSK => 1
> Are there Oric disk images in EDSK format (that's used by the Amstrad CPC and ZX +3).

We have tryed EDSK file format,the main problem is SEDORIC ( oric OS ) reads 256 sectors by track, and EDSK goes with 512. Converting DSK to IMG seems to work fine.

**Pull request merged**
